import type { ModeManifest } from "@/apps/types";

export const modes: ModeManifest[] = [
  {
    id: "default",
    name: "默认桌面",
    desktopApps: [
      "industry_hub",
      "recruiting_desk",
      "project_ops",
      "deep_research_hub",
      "financial_document_bot",
      "social_media_autopilot",
      "website_seo_studio",
      "language_learning_desk",
      "tech_news_digest",
      "solo_ops",
      "solutions_hub",
      "morning_brief",
      "meeting_copilot",
      "personal_crm",
      "inbox_declutter",
      "support_copilot",
      "second_brain",
      "email_assistant",
      "deal_desk",
      "family_calendar",
      "habit_tracker",
      "health_tracker",
      "creator_radar",
      "content_repurposer",
      "media_ops",
      "creative_studio",
      "knowledge_vault",
      "account_center",
      "task_manager",
      "runtime_console",
      "publisher",
      "settings",
    ],
    dockApps: [
      "solo_ops",
      "industry_hub",
      "media_ops",
      "creative_studio",
      "knowledge_vault",
      "account_center",
      "task_manager",
      "runtime_console",
      "publisher",
      "settings",
    ],
  },
  {
    id: "creator",
    name: "AI 文案",
    desktopApps: [
      "industry_hub",
      "recruiting_desk",
      "project_ops",
      "deep_research_hub",
      "financial_document_bot",
      "social_media_autopilot",
      "website_seo_studio",
      "language_learning_desk",
      "tech_news_digest",
      "solo_ops",
      "solutions_hub",
      "morning_brief",
      "meeting_copilot",
      "personal_crm",
      "inbox_declutter",
      "support_copilot",
      "second_brain",
      "email_assistant",
      "deal_desk",
      "family_calendar",
      "habit_tracker",
      "health_tracker",
      "creator_radar",
      "content_repurposer",
      "media_ops",
      "creative_studio",
      "knowledge_vault",
      "account_center",
      "task_manager",
      "runtime_console",
      "publisher",
      "settings",
    ],
    dockApps: [
      "solo_ops",
      "industry_hub",
      "media_ops",
      "creative_studio",
      "knowledge_vault",
      "account_center",
      "task_manager",
      "runtime_console",
      "publisher",
      "settings",
    ],
  },
  {
    id: "solo",
    name: "工作流",
    desktopApps: [
      "industry_hub",
      "recruiting_desk",
      "project_ops",
      "deep_research_hub",
      "financial_document_bot",
      "social_media_autopilot",
      "website_seo_studio",
      "language_learning_desk",
      "tech_news_digest",
      "solo_ops",
      "solutions_hub",
      "morning_brief",
      "meeting_copilot",
      "personal_crm",
      "inbox_declutter",
      "support_copilot",
      "second_brain",
      "email_assistant",
      "deal_desk",
      "family_calendar",
      "habit_tracker",
      "health_tracker",
      "creator_radar",
      "content_repurposer",
      "media_ops",
      "creative_studio",
      "publisher",
      "knowledge_vault",
      "account_center",
      "task_manager",
      "runtime_console",
      "settings",
    ],
    dockApps: [
      "solo_ops",
      "industry_hub",
      "media_ops",
      "creative_studio",
      "publisher",
      "task_manager",
      "settings",
    ],
  },
];

export function getMode(modeId: ModeManifest["id"]) {
  return modes.find((mode) => mode.id === modeId) ?? modes[0];
}
